### ISSUE TITLE
Wrong voice utterance output

### ISSUE THREAD

**Issue by helenvarley** [foobarlab/UpStage-Video-Hack#110]
on the new stage created today for the performance, when i tried to test the voice of pig, the avatar spoke with a totally other voice & also totally other text - it was reading the log from the test we did with london on friday!!! & not at all saying what i was typing.

**Comment by helenvarley** [comment]
this bug is also happening in the voice test on the upload avatar screen! :(

**Comment by foobarlab** [comment]
This bug probably is also related to the reverse-proxy infrastructure (like #108). To reproduce this bug there is too less information given so this may be put into an "invalid" or "wontfix" state.

**Comment by helenvarley** [comment]
i tried doing exactly the same things as i did before we had this bug:
1. create a new stage
2. assign an avatar to it
3. go to the stage & speak with the avatar

i did not get the voice loop problem.

but it is something to be wary of, since there could be many occasions where we are not able to have the server immediately restarted to solve it. do you think the bug ONLY happened within the graz network? or might others viewing the stage have also heard the wrong text? if it's only within the local network then is the solution to clear caches?

**Comment by foobarlab** [comment]
Clearing the whole browser cache could fix the problem. Probably also clearing the reverse-proxy-cache could help.
Like #108 this bug is most likely not related to programming but installing UpStage.

**Comment by foobarlab** [comment]
Seems to have been an issue with installation and having missed to clear the reverse-proxy cache.
