### ISSUE TITLE
Safari (WebKit) on Windows: No focus for text input (when displaying stage swf)

### ISSUE THREAD

**Issue by foobarlab** [foobarlab/UpStage-Video-Hack#114]
It is not possible to enter text to the chat field on Safari/Windows. This is due a bug in WebKit which prevents keyboard focus when `wmode` of the swf is set to `transparent`.

See also:
http://stackoverflow.com/questions/7871189/flash-textfield-safari-cant-type-into-text-field-when-wmode-is-set-to-tra
http://stackoverflow.com/questions/594821/object-focus-problem-with-safari-and-chrome-browsers
http://stackoverflow.com/questions/886864/differences-between-using-wmode-transparent-opaque-or-window-for-an-embe
http://helpx.adobe.com/flash/kb/flash-object-embed-tag-attributes.html#main_Browser_support_for_Window_Mode__wmode__values/fplayer10.1_hardware_acceleration_04.html

**Comment by foobarlab** [comment]
Looks like `wmode` set to `direct` gives the best possible performance boost (works since Flash version 10). See: http://labs.almerblank.com/2011/03/the-wmode-embed-parameter-de-mystified/

**Comment by helenvarley** [comment]
tested on mac using firefox, chrome & safari - able to input text both as audience & holding an av. it works! :)

**Comment by foobarlab** [comment]
tested and confirmed success on linux using chromium, chrome, firefox and opera.
