### ISSUE TITLE
Streaming: transcode WebRTC stream to RTMP stream

### ISSUE THREAD

**Issue by foobarlab** [foobarlab/UpStage-Video-Hack#117]
The new WebRTC streaming functionality of some browsers seems a nice addition. So it would be nice to be able to stream from any WebRTC-capable browser without having to install Flash.

It should work this way:
- the browser sends its WebRTC stream to the server where it is received by [GStreamer](http://gstreamer.freedesktop.org/)
- on the server-side it is transcoded to a RTMP stream and sent to a RTMP streaming server
- the RTMP streaming server publishes it to UpStage client

Is GStreamer already providing a working WebRTC client implementation?

**Comment by benbowler** [comment]
+1

**Comment by terbooter** [comment]
+1

**Comment by foobarlab** [comment]
Thanks for upvoting! Sadly this project ("upstage-video-hack") is no more further developed and got replaced by its successor: https://github.com/AUTUpStageTeam/UpStage
If you are voting for a RTMP <-> WebRTC solution please consult the GStreamer Website (http://gstreamer.freedesktop.org/) which might offer solutions for this specific use case or consider using an already working Solution like https://github.com/meetecho/janus-gateway, http://www.kurento.org/ or https://red5pro.com/.
Thanks and happy coding! :smile:
