### ISSUE TITLE
Workshop: Access right properties for "edit stage" (HTML backend)

### ISSUE THREAD

**Issue by foobarlab** [foobarlab/UpStage-Video-Hack#45]
Apparantely the functionality to assign access rights seems not implemented yet. In the workshop these properties are visible but unavailable to the user (section "Users who can access and edit this stage"). To avoid confusion these properties should be hidden until implemented.

**Comment by helenvarley** [comment]
yes, it was not able to be implemented in time for the 2.4.2 release, so it has a sign saying that the feature is still in development; this was done in order not to slow down the release further (by either implementing it, or taking that bit out of the interface). it should be implemented in 2.4.3

**Comment by foobarlab** [comment]
In general funtionality which is not working or not implemented yet should be either hidden or deleted from the source code. Otherwise it is neither clear for users nor cleanly understandable for developers why half-baked funtionality is kept.

**Comment by foobarlab** [comment]
Fixed in 4053dfd8530d99053ed4d04b882a5a232fde654f.
