### ISSUE TITLE
Scrolling through available media is very slow (HTML backend)

### ISSUE THREAD

**Issue by foobarlab** [foobarlab/UpStage-Video-Hack#47]
When reviewing the availabe media scrolling through the "gallery" takes ages. To speed up access to media an alternative view should be accessible which allows faster browsing.

**Comment by helenvarley** [comment]
this is currently the highest priority for the students to fix: https://sourceforge.net/apps/trac/upstage/ticket/176
it really makes the media manager part of 8081 extremely difficult to use :(

**Comment by foobarlab** [comment]
If a fix is found code can be sent to this repository by pull request. As the development here is independent from the students development code is not synchronized. Behaviour of bugs can not be expected to be the same.

**Comment by foobarlab** [comment]
Some more notes on the "Edit Media" view which shows the available media:
- First, it is questionable if a slider can fulfill the requirement for browsing large amounts of media? So what are the alternatives here?
- Second, the way the slider is implemented currently has some major issues:
  - the displayed media is always the original media (meaning .swf instead of a potentially smaller thumbnail, so better load the thumbnail instead of huge swf files)
  - all(!) media seems to be loaded at once (better do lazy loading; just load the media which is visible to the user and proceed loading while scrolling)
  - caching seems not functional, so each time the whole set has to be sent by the server again (better make use of caching mechanisms, like the plain browser cache)

**Comment by helenvarley** [comment]
vicki & i met with the students this morning; they are working on this as the most urgent highest priority, but they said that they have had some challenges implementing lazy loading - didn't get details from them tho. i will ask them to post an update to the dev list. 
personally i think a slider is not really necessary - would be better to have a text list & perhaps some way to get a thumbnail if you hover over an image, so that you can see if it is the one you want. & definitely to have the default setting be that user's media. we have to go for functionality first, & "pretty" second ;)

**Comment by foobarlab** [comment]
Maybe doing a mockup first and verifying usability would be a good approach then. Lazy loading can be tricky when done at the current state as the code throughout lacks clear structure and abstraction. Also proper testing to validate code correctness will be quite hard because the code is not prepared for (automated) tests yet.

In my opinion it would be good to rethink the webinterface and integrate a JavaScript framework which provides both abstraction and layout facilities to kept code structured and simple. I have proposed this already in #55. And in the end even being "pretty" wouldn't be a conflict.

**Comment by foobarlab** [comment]
<a href="https://github.com/mleibman/SlickGrid">SlickGrid</a> is probably the way to go.

**Comment by foobarlab** [comment]
Obsolete by #70.
