### ISSUE TITLE
Unable to delete media (HTML backend)

### ISSUE THREAD

**Issue by foobarlab** [foobarlab/UpStage-Video-Hack#49]
It seems impossible to delete media once added. The button "Delete Media" does not work.

**Comment by helenvarley** [comment]
that's not the case on http://upstage.org.nz:8081/ - or at least, it wasn't last time i deleted something. you do get incorrect deletion messages (telling you that the stage is being deleted, rather than the media item) but it does delete, as far as i'm aware.

**Comment by foobarlab** [comment]
In general this and all other tickets just refer to the code here in GitHub, therefore it does not play a role if it works on http://upstage.org.nz:8081 or not. Nonetheless, it could be an indication that the code here is also affected.

This ticket just refers to the deletion of media, not stages. If deletion of stages also does not work based on this code a new ticket should be created. Furthermore it can not be confirmed that deletion of media works.

**Comment by foobarlab** [comment]
Obsoleted by #70.
