### ISSUE TITLE
Media upload not working in all browsers (HTML backend)

### ISSUE THREAD

**Issue by helenvarley** [foobarlab/UpStage-Video-Hack#83]
The upload currently seems only to work on Firefox. Additional browsers to test are Safari, Chrome/Chromium, Opera, Internet Exploder, etc.

**Comment by foobarlab** [comment]
Problem is probably that a JavaScrip error prevents processing the upload. Should probably be already fixed in the current developer version.

**Comment by foobarlab** [comment]
Actually it was the case that it is not directly the upload which does not work but the "add media" panel just was not displayed on some browsers.
